include common.mk

all:
	make clean
	COVERAGE=1 LANG=C LC_ALL=C ../asn2dataModel/asn2dataModel.py -toSMP2 DataTypesSimulink.asn || exit 1
	COVERAGE=1 LANG=C LC_ALL=C ${COVERAGE} run -a ../smp2/smp2asn.py >/dev/null 2>&1 ; exit 0
	COVERAGE=1 LANG=C LC_ALL=C ${COVERAGE} run -a ../smp2/smp2asn.py -h >/dev/null 2>&1 ; exit 0
	COVERAGE=1 LANG=C LC_ALL=C ${COVERAGE} run -a ../smp2/smp2asn.py -z >/dev/null 2>&1 ; exit 0
	COVERAGE=1 LANG=C LC_ALL=C ${COVERAGE} run -a ../smp2/smp2asn.py -o smp2.asn -a nonexisting.asn nonexisting.cat >/dev/null 2>&1 ; exit 0
	COVERAGE=1 LANG=C LC_ALL=C ${COVERAGE} run -a ../smp2/smp2asn.py -o smp2.asn -a DataTypesSimulink.asn -v -p datatypessimulink.cat >/dev/null 2>&1 || exit 1
	COVERAGE=1 LANG=C LC_ALL=C ${COVERAGE} annotate -d . ../smp2/*.py ../commonPy/*.py || exit 1
	./checkCoverage.pl ___smp2_smp2asn.py,cover || { echo smp2asn.py ; ./review.pl ___smp2_smp2asn.py,cover | less -RS ; exit 1 ; }

clean:
	${COVERAGE} erase
	rm -f ___*.py,cover smp2.asn datatypessimulink.cat
