VPATH=.:../aadl2glueC:../commonPy

PYSRC_B := aadl2glueC.py asynchronousTool.py synchronousTool.py ada_B_mapper.py c_B_mapper.py og_B_mapper.py simulink_B_mapper.py scade6_B_mapper.py pyside_B_mapper.py # vhdl_B_mapper.py
PYSRC_B_COVER := $(PYSRC_B:%.py=___aadl2glueC_%.py,cover)

.PHONY:	check

all:	$(PYSRC_B_COVER) check

DataView.aadl:	DataTypesSimulink.asn
	../asn2aadlPlus/asn2aadlPlus.py $< $@

DataViewVHDL.aadl:	DataTypesSimulinkVHDL.asn
	../asn2aadlPlus/asn2aadlPlus.py $< $@
 
___aadl2glueC_%.py,cover:	../aadl2glueC/%.py mini_cv.aadl DataView.aadl DataViewVHDL.aadl
	@echo Update required: $@ depends on $?
	$(MAKE) -f Makefile.M2C clean
	mkdir -p output
	rm -rf output/*
	# coverage run -a ../aadl2glueC.py -o output -verbose mini_cv_vhdl.aadl DataViewVHDL.aadl >/dev/null
	COVERAGE=1 LANG=C LC_ALL=C python-coverage run -a ../aadl2glueC/aadl2glueC.py -o output -verbose mini_cv.aadl DataView.aadl >/dev/null
	COVERAGE=1 LANG=C LC_ALL=C python-coverage run -a ../aadl2glueC/aadl2glueC.py -o output -verbose -useOSS mini_cv.aadl DataView.aadl >/dev/null
	COVERAGE=1 LANG=C LC_ALL=C python-coverage annotate -d . ../aadl2glueC/*.py ../commonPy/*.py

check:
	@for i in $(PYSRC_B_COVER) ; do echo Checking $$i ... ; ./checkCoverage.pl $$i || { ( echo $$i ; ./review.pl $$i ) | less -RS ; echo $$i had issues... ; exit 1 ; } ; done

clean:
	python-coverage erase
	rm -f ./___*,cover
	rm -rf output/
